const { contextBridge, ipcRenderer, webUtils } = require('electron')

contextBridge.exposeInMainWorld('automation', {
  defaultOutputDirectory: () => ipcRenderer.invoke('app:default-output-directory'),
  selectDirectory: () => ipcRenderer.invoke('dialog:select-directory'),
  selectQuestions: () => ipcRenderer.invoke('dialog:select-questions'),
  selectProductWorkbook: () => ipcRenderer.invoke('dialog:select-product-workbook'),
  listDevices: () => ipcRenderer.invoke('automation:devices'),
  listEntries: () => ipcRenderer.invoke('automation:entries'),
  listTasks: () => ipcRenderer.invoke('automation:tasks'),
  startPreview: (serial, streamId) => ipcRenderer.invoke('automation:preview-start', serial, streamId),
  stopPreview: (serial, streamId) => ipcRenderer.invoke('automation:preview-stop', serial, streamId),
  acknowledgePreview: (serial, streamId, sequence) => ipcRenderer.send('automation:preview-ack', serial, streamId, sequence),
  onPreview: callback => ipcRenderer.on('automation:preview-event', (_event, value) => callback(value)),
  importQuestions: payload => ipcRenderer.invoke('questions:import', payload),
  importProductWorkbook: file => ipcRenderer.invoke('product-questions:import', file),
  getPathForFile: file => webUtils.getPathForFile(file),
  start: payload => ipcRenderer.invoke('automation:start', payload),
  retryFailed: payload => ipcRenderer.invoke('automation:retry-failed', payload),
  stop: serial => ipcRenderer.invoke('automation:stop', serial),
  copyText: text => ipcRenderer.invoke('clipboard:write', text),
  exportLog: text => ipcRenderer.invoke('log:export', text),
  getUpdateState: () => ipcRenderer.invoke('update:state'),
  checkForUpdate: () => ipcRenderer.invoke('update:check'),
  downloadUpdate: () => ipcRenderer.invoke('update:download'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  onLog: callback => ipcRenderer.on('automation:log', (_event, text) => callback(text)),
  onProgress: callback => ipcRenderer.on('automation:progress', (_event, value) => callback(value)),
  onFinished: callback => ipcRenderer.on('automation:finished', (_event, result) => callback(result)),
  onUpdateState: callback => ipcRenderer.on('update:state', (_event, value) => callback(value)),
})
